Flyttet data om siste periode med overgangsstønad
navikt/familie-ef-sak pull request #2601
Opened 2024-05-27 07:58 UTC by gunnsteingarmo

### Hvorfor er denne endringen nødvendig? ✨
Vil ikke legge til eller gjøre endringer på data som brukes på tidligere vedtakshistorikk.

- Har flyttet data om siste periode med overgangsstønad fra GrunnlagsdataPeriodeHistorikkOvergangsstønad til en ny dataklasse. Denne blir brukt på TidligereInnvilgetVedtak til det nye feltet sistePeriodeMedOvergangsstønad.

2024-05-27 11:56 UTC, olekvernberg approved these changes

2024-05-28 09:18 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/GrunnlagsdataPeriodeHistorikkOvergangsstønad.kt
> -    val samordningsfradrag: Int?,
Forslag: 

Beholde disse i grunnlagsdata.

2024-05-28 09:18 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/sak/opplysninger/personopplysninger/SistePeriodeMedOvergangsstønad.kt
> +data class SistePeriodeMedOvergangsstønad(
Slette denne?

2024-05-28 09:19 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/TidligereVedtaksperioderDto.kt
> +        sistePeriodeMedOvergangsstønad = this.sistePeriodeMedOvergangsstønad?.tilDto(),
Bruk this.periodeHistorikkOvergangsstønad - hent siste, lag dto..

2024-05-28 10:16 UTC, ma10s requested changes
Sjekk om vi kan klare oss uten SistePeriodeMedOvergangsstønad i grunnlagsdata :D

2024-05-28 11:01 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/TidligereVedtaksperioderDto.kt
> +    return if (sistePeriode != null) {
Bruke when?

2024-05-28 11:02 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/TidligereVedtaksperioderDto.kt
> +    val sistePeriodeMedOvergangsstønad: SistePeriodeMedOvergangsstønadDto? = null,
= null - trenger vi denne her?

2024-05-28 11:04 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/TidligereVedtaksperioderDto.kt
> +private fun List<GrunnlagsdataPeriodeHistorikkOvergangsstønad>.tilSistePeriodeDto(): SistePeriodeMedOvergangsstønadDto? {
Kan vi lage en test her?

2024-05-28 11:07 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/TidligereVedtaksperioderDto.kt
> +    return if (sistePeriode != null) {
Eller .let :D

2024-05-28 11:37 UTC, gunnsteingarmo commented on src/main/kotlin/no/nav/familie/ef/sak/vilkår/dto/TidligereVedtaksperioderDto.kt
> +    val sistePeriodeMedOvergangsstønad: SistePeriodeMedOvergangsstønadDto? = null,
Uten = null  - må det settes en verdi andre steder i koden.

2024-05-28 12:08 UTC, ma10s approved these changes
Denne er fin!

2024-05-29 14:01 UTC, charliemidtlyng approved these changes

2024-05-30 11:31 UTC, merged